### ISSUE TITLE
I tried to delete a prayer request

### ISSUE THREAD

**Issue by neutrinog** [neutrinog/prayerchart#101]
Notes
======
I tried to delete a prayer request

Environment
======
Environment Key | Value
:----: | :----:
version | 1.2.0
build | 11
UDID | 31677866df8d247c
Android Release | 4.1.1
Android SDK | 16
Brand | asus
Device | TF201
Stack trace
======
```java
java.lang.NullPointerException
	at android.app.DialogFragment.onActivityCreated(DialogFragment.java:469)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:848)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1035)
	at android.app.BackStackRecord.popFromBackStack(BackStackRecord.java:712)
	at android.app.FragmentManagerImpl.popBackStackState(FragmentManager.java:1492)
	at android.app.FragmentManagerImpl$4.run(FragmentManager.java:479)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1397)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:426)
	at android.os.Handler.handleCallback(Handler.java:615)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4745)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
	at dalvik.system.NativeStart.main(Native Method)

```
Log history
======
```java
2/5/16 1:59 PM  I/com.neutrinographics.prayersheet.tasks.UploadFeedbackTask: Submitted bug report
     
```

**Comment by neutrinog** [comment]
we can't reproduce this.
