### ISSUE TITLE
Allow sharing of prayer requests. If they have ...

### ISSUE THREAD

**Issue by neutrinog** [neutrinog/prayerchart#158]
# Notes

Allow sharing of prayer requests. If they have the app it will open up in the app otherwise it will just send a text. Sort like groupme
# Environment

| Environment Key | Value |
| :-: | :-: |
| version | 1.5.0 |
| build | 14 |
| UDID | 29fc019efc78c5c1 |
| Android Release | 5.1.1 |
| Android SDK | 22 |
| Brand | OnePlus |
| Device | OnePlus |
# Log history

``` java
9/9/16 8:47 AM  E/com.neutrinographics.prayersheet.App: Failed to generate the keys
java.security.GeneralSecurityException: MAC stored in civ does not match computed MAC.
    at com.tozny.crypto.android.AesCbcWithIntegrity.decrypt(AesCbcWithIntegrity.java:409)
    at com.tozny.crypto.android.AesCbcWithIntegrity.decryptString(AesCbcWithIntegrity.java:372)
    at com.tozny.crypto.android.AesCbcWithIntegrity.decryptString(AesCbcWithIntegrity.java:387)
    at com.neutrinographics.prayersheet.App.authorize(App.java:151)
    at com.neutrinographics.prayersheet.tasks.AuthenticateTask.start(AuthenticateTask.java:25)
    at org.unfoldingword.tools.taskmanager.ManagedTask.run(ManagedTask.java:78)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:818)

9/9/16 8:47 AM  E/com.neutrinographics.prayersheet.App: Failed to generate the keys
java.security.GeneralSecurityException: MAC stored in civ does not match computed MAC.
    at com.tozny.crypto.android.AesCbcWithIntegrity.decrypt(AesCbcWithIntegrity.java:409)
    at com.tozny.crypto.android.AesCbcWithIntegrity.decryptString(AesCbcWithIntegrity.java:372)
    at com.tozny.crypto.android.AesCbcWithIntegrity.decryptString(AesCbcWithIntegrity.java:387)
    at com.neutrinographics.prayersheet.App.authorize(App.java:151)
    at com.neutrinographics.prayersheet.tasks.AuthenticateTask.start(AuthenticateTask.java:25)
    at org.unfoldingword.tools.taskmanager.ManagedTask.run(ManagedTask.java:78)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:818)

9/6/16 8:46 AM  I/com.neutrinographics.prayersheet.tasks.UploadFeedbackTask: Submitted bug report


```

**Comment by neutrinog** [comment]
Issue moved to [neutrinog/prayersheet #68](https://github.com/neutrinog/prayersheet/issues/68) via [**ZenHub**](https://www.zenhub.com/)
