### ISSUE TITLE
I recommend swipe to clear/mark as done a request

### ISSUE THREAD

**Issue by neutrinog** [neutrinog/prayerchart#79]
Notes
======
I recommend swipe to clear/mark as done a request

Environment
======
Environment Key | Value
:----: | :----:
version | 1.0.1
build | 8
UDID | dd19773da22f5f
Android Release | 5.0
Android SDK | 21
Brand | Verizon
Device | kltevzw
Log history
======
```java
1/11/16 9:25 AM  W/com.neutrinographics.prayersheet.home.CreateContactDialog: Failed to copy temp image into internal storage
java.io.FileNotFoundException: Source '/storage/emulated/0/Prayer Chart/temp.png' does not exist
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1074)
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1038)
	at com.neutrinographics.prayersheet.home.CreateContactDialog.addContact(CreateContactDialog.java:129)
	at com.neutrinographics.prayersheet.home.CreateContactDialog.access$100(CreateContactDialog.java:36)
	at com.neutrinographics.prayersheet.home.CreateContactDialog$3.onClick(CreateContactDialog.java:106)
	at android.view.View.performClick(View.java:5156)
	at android.view.View$PerformClick.run(View.java:20755)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5835)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

     
```

**Comment by neutrinog** [comment]
will will not do this because it makes other parts of the ui complicated. See #103
